# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fedbc5537552c70f0470723105b46a31c2f864188d7f648e498b28508e5efa230df6a5088ee4d48e6674f1c58668833c6bd527a4d3e0670cb38498e321a46278

test:
  secret_key_base: 7ca818a6bf2844f81b2e1ebc284d5d96a79d7d97be97caf583e8a1886eafa0b0aa0dc83dabe3560871d6b8de1b0cd99d2073e99f77c46e0bf014dcf2a8d351f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
